#define MSG_ENABLE_CONFIG_REBOOT	"MSG_ENABLE_CONFIG_REBOOT"
#define MSG_1D_FDD				"MSG_1D_FDD"
#define MSG_NO_1DD				"MSG_NO_1DD"
#define MSG_RESET_CPU				"MSG_RESET_CPU"
#define MSG_EXIT					"MSG_EXIT"
#define MSG_FAILED_RESET			"MSG_FAILED_RESET"
#define MSG_REBOOT_ENABLE_CONFIG	"MSG_REBOOT_ENABLE_CONFIG"
#define MSG_SEARCH_ROM				"MSG_SEARCH_ROM"
#define MSG_ROM_FOUND_LAUNCH		"MSG_ROM_FOUND_LAUNCH"
#define MSG_REWIND_LOAD_TAPE		"MSG_REWIND_LOAD_TAPE"
#define MSG_REWIND_SAVE_TAPE		"MSG_REWIND_SAVE_TAPE"
#define MSG_SAME_DISK_IMAGE		"MSG_SAME_DISK_IMAGE"

unsigned char *mgettext(unsigned char *key);
